const ROLES = {
  ADMIN:    'admin',
  STAFF:    'staff',
  TRAINER:  'trainer',
  CUSTOMER: 'customer',
};

const ROLE_GROUPS = {
  INTERNAL_STAFF: [ROLES.ADMIN, ROLES.STAFF],
  ADMIN_ONLY:     [ROLES.ADMIN],
  TRAINER_ONLY:   [ROLES.TRAINER],
  CUSTOMER_ONLY:  [ROLES.CUSTOMER],
  ALL_STAFF:      [ROLES.ADMIN, ROLES.STAFF, ROLES.TRAINER],
};

module.exports = { ROLES, ROLE_GROUPS };